### ISSUE TITLE
Finish and release Zeykerokyu

### ISSUE THREAD

**Issue by Willem3141** [Willem3141/navi-reykunyu#143]
This is a tracking issue to keep track of what still needs to happen before Zeykerokyu (vocab study tool) can be released.

- [x] implement preprocessing word data (#138)
- [x] finish #133 and merge it
- [x] update Zeykerokyu to support the new word ID system
- [x] implement user creation (#61)
- [x] add landing page for Zeykerokyu
- [ ] launch it :rocket:
